import "server-only";

import type {
  BusinessIntentDefinition,
  CapabilityDefinition,
  SlotRequirement,
} from "@/modules/brain/runtime/contracts";
import { plannedAgentCapabilities } from "@/modules/brain/runtime/agent-capability-expansion";

const querySlot: SlotRequirement = {
  clarification: "Que busqueda quieres realizar?",
  name: "query",
  required: true,
  type: "string",
};

const customerNameSlot: SlotRequirement = {
  clarification: "Cual es el nombre del cliente?",
  name: "nombre",
  required: true,
  type: "string",
};

const productNameSlot: SlotRequirement = {
  clarification: "Cual es el nombre del producto o servicio?",
  name: "nombre",
  required: true,
  type: "string",
};

const blogTopicSlot: SlotRequirement = {
  clarification: "Sobre que tema quieres generar el articulo?",
  name: "topic",
  required: true,
  type: "string",
};

const quoteItemsSlot: SlotRequirement = {
  clarification: "Que productos, cantidades y precios debe incluir la cotizacion?",
  name: "items",
  required: true,
  type: "array",
};

const taskTitleSlot: SlotRequirement = {
  clarification: "Cual es el titulo de la tarea?",
  name: "title",
  required: true,
  type: "string",
};

const customerQuerySlot: SlotRequirement = {
  clarification: "A que cliente te refieres?",
  name: "customerQuery",
  required: true,
  type: "string",
};

const productQuerySlot: SlotRequirement = {
  clarification: "A que producto te refieres?",
  name: "productQuery",
  required: true,
  type: "string",
};

const warehouseSlot: SlotRequirement = {
  clarification: "En que bodega debe hacerse la operacion?",
  name: "warehouse",
  required: true,
  type: "string",
};

const originWarehouseSlot: SlotRequirement = {
  clarification: "Desde que bodega debo transferir el stock?",
  name: "originWarehouse",
  required: true,
  type: "string",
};

const destinationWarehouseSlot: SlotRequirement = {
  clarification: "Hacia que bodega debo transferir el stock?",
  name: "destinationWarehouse",
  required: true,
  type: "string",
};

const quantitySlot: SlotRequirement = {
  clarification: "Que cantidad debo usar?",
  name: "quantity",
  required: true,
  type: "number",
};

const quoteReferenceSlot: SlotRequirement = {
  clarification: "A que cotizacion o proforma te refieres?",
  name: "quoteReference",
  required: true,
  type: "string",
};

const saleReferenceSlot: SlotRequirement = {
  clarification: "A que venta te refieres?",
  name: "saleReference",
  required: true,
  type: "string",
};

const accountReferenceSlot: SlotRequirement = {
  clarification: "A que cuenta, factura o cliente se aplica el cobro?",
  name: "accountReference",
  required: true,
  type: "string",
};

const conversationReferenceSlot: SlotRequirement = {
  clarification: "A que conversacion o cliente de Inbox te refieres?",
  name: "conversationReference",
  required: true,
  type: "string",
};

const assigneeSlot: SlotRequirement = {
  clarification: "A quien debo asignarlo?",
  name: "assignee",
  required: true,
  type: "string",
};

const contentSlot: SlotRequirement = {
  clarification: "Que contenido debo usar?",
  name: "content",
  required: true,
  type: "string",
};

function binding(capabilityId: string, skillId: string, status = "implemented") {
  return {
    capabilityId,
    priority: 100,
    skillId,
    status: status as "implemented" | "planned" | "blocked",
    version: "1.0.0",
  };
}

const stage2CapabilityContracts: CapabilityDefinition[] = [
  {
    description: "Actualizar datos basicos de un cliente existente.",
    enabled: true,
    id: "crm.customer.update",
    kind: "command",
    module: "crm",
    name: "Actualizar cliente",
    requiredPermissions: ["crm.customers.edit"],
    skillBindings: [binding("crm.customer.update", "crm.customer.update")],
    status: "implemented",
    version: "1.0.0",
  },
  {
    description: "Consultar historial comercial, ventas, cotizaciones y seguimientos de un cliente.",
    enabled: true,
    id: "crm.customer.history",
    kind: "query",
    module: "crm",
    name: "Historial de cliente",
    requiredPermissions: ["crm.customers.view", "sales.orders.view"],
    skillBindings: [binding("crm.customer.history", "crm.customer.history")],
    status: "implemented",
    version: "1.0.0",
  },
  {
    description: "Consultar seguimientos pendientes o recientes de CRM.",
    enabled: true,
    id: "crm.followup.query",
    kind: "query",
    module: "crm",
    name: "Consultar seguimientos",
    requiredPermissions: ["crm.followups.view"],
    skillBindings: [binding("crm.followup.query", "crm.followup.query")],
    status: "implemented",
    version: "1.0.0",
  },
  {
    description: "Crear un seguimiento concreto para un cliente o una venta.",
    enabled: true,
    id: "crm.followup.create",
    kind: "command",
    module: "crm",
    name: "Crear seguimiento",
    requiredPermissions: ["crm.followups.create"],
    skillBindings: [binding("crm.followup.create", "crm.followup.create")],
    status: "implemented",
    version: "1.0.0",
  },
  {
    description: "Actualizar datos comerciales, fiscales o de precio de un producto.",
    enabled: true,
    id: "catalog.product.update",
    kind: "command",
    module: "catalog",
    name: "Actualizar producto",
    requiredPermissions: ["catalog.products.edit"],
    skillBindings: [binding("catalog.product.update", "catalog.product.update")],
    status: "implemented",
    version: "1.0.0",
  },
  {
    description: "Validar que un producto tenga datos minimos para venderse, comprarse o inventariarse.",
    enabled: true,
    id: "catalog.product.validate",
    kind: "analysis",
    module: "catalog",
    name: "Validar producto",
    requiredPermissions: ["catalog.products.view"],
    skillBindings: [binding("catalog.product.validate", "catalog.product.validate")],
    status: "implemented",
    version: "1.0.0",
  },
  {
    description: "Inicializar stock de un producto en una bodega especifica.",
    enabled: true,
    id: "catalog.product.stock.initialize",
    kind: "command",
    module: "catalog",
    name: "Inicializar stock de producto",
    requiredPermissions: ["catalog.products.edit", "inventory.stock.adjust"],
    skillBindings: [
      binding("catalog.product.stock.initialize", "catalog.product.stock.initialize"),
    ],
    status: "implemented",
    version: "1.0.0",
  },
  {
    description: "Ajustar existencias de inventario con evidencia y trazabilidad.",
    enabled: true,
    id: "inventory.stock.adjust",
    kind: "command",
    module: "inventory",
    name: "Ajustar stock",
    requiredPermissions: ["inventory.stock.adjust"],
    skillBindings: [binding("inventory.stock.adjust", "inventory.stock.adjust")],
    status: "implemented",
    version: "1.0.0",
  },
  {
    description: "Transferir stock entre bodegas sin perder trazabilidad.",
    enabled: true,
    id: "inventory.stock.transfer",
    kind: "command",
    module: "inventory",
    name: "Transferir stock",
    requiredPermissions: ["inventory.stock.adjust"],
    skillBindings: [binding("inventory.stock.transfer", "inventory.stock.transfer")],
    status: "implemented",
    version: "1.0.0",
  },
  {
    description: "Agregar productos o servicios a una cotizacion existente.",
    enabled: true,
    id: "quotes.item.add",
    kind: "command",
    module: "quotes",
    name: "Agregar item a cotizacion",
    requiredPermissions: ["quotes.edit"],
    skillBindings: [binding("quotes.item.add", "quotes.item.add")],
    status: "implemented",
    version: "1.0.0",
  },
  {
    description: "Calcular totales, impuestos y descuentos de una cotizacion.",
    enabled: true,
    id: "quotes.total.calculate",
    kind: "query",
    module: "quotes",
    name: "Calcular cotizacion",
    requiredPermissions: ["quotes.view"],
    skillBindings: [binding("quotes.total.calculate", "quotes.total.calculate")],
    status: "implemented",
    version: "1.0.0",
  },
  {
    description: "Consultar cotizaciones vencidas o sin respuesta para seguimiento.",
    enabled: true,
    id: "quotes.expired.query",
    kind: "query",
    module: "quotes",
    name: "Consultar cotizaciones vencidas",
    requiredPermissions: ["quotes.view"],
    skillBindings: [binding("quotes.expired.query", "quotes.expired.query")],
    status: "implemented",
    version: "1.0.0",
  },
  {
    description: "Confirmar una cotizacion como venta cuando cumple validaciones.",
    enabled: true,
    id: "quotes.sale.confirm",
    kind: "command",
    module: "quotes",
    name: "Confirmar cotizacion como venta",
    requiredPermissions: [
      "quotes.status.change",
      "sales.orders.create",
      "sales.orders.status.change",
    ],
    skillBindings: [binding("quotes.sale.confirm", "quotes.sale.confirm")],
    status: "implemented",
    version: "1.0.0",
  },
  {
    description: "Consultar detalle completo de una venta.",
    enabled: true,
    id: "sales.order.detail",
    kind: "query",
    module: "sales",
    name: "Detalle de venta",
    requiredPermissions: ["sales.orders.view"],
    skillBindings: [binding("sales.order.detail", "sales.order.detail")],
    status: "implemented",
    version: "1.0.0",
  },
  {
    description: "Generar cuenta por cobrar desde una venta confirmada.",
    enabled: true,
    id: "sales.receivable.generate",
    kind: "command",
    module: "sales",
    name: "Generar cuenta por cobrar",
    requiredPermissions: ["sales.orders.edit", "payments.accounts.manage"],
    skillBindings: [binding("sales.receivable.generate", "sales.receivable.generate")],
    status: "implemented",
    version: "1.0.0",
  },
  {
    description: "Preparar despacho desde una venta lista para entregar.",
    enabled: true,
    id: "sales.dispatch.prepare",
    kind: "command",
    module: "sales",
    name: "Preparar despacho de venta",
    requiredPermissions: ["sales.orders.edit", "dispatch.orders.create"],
    skillBindings: [binding("sales.dispatch.prepare", "sales.dispatch.prepare")],
    status: "implemented",
    version: "1.0.0",
  },
  {
    description: "Registrar cobro o abono contra una cuenta por cobrar.",
    enabled: true,
    id: "payments.payment.register",
    kind: "command",
    module: "payments",
    name: "Registrar cobro",
    requiredPermissions: ["payments.accounts.manage"],
    skillBindings: [binding("payments.payment.register", "payments.payment.register")],
    status: "implemented",
    version: "1.0.0",
  },
  {
    description: "Consultar estado de cuenta de un cliente o proveedor.",
    enabled: true,
    id: "payments.account.statement",
    kind: "query",
    module: "payments",
    name: "Estado de cuenta",
    requiredPermissions: ["payments.accounts.view"],
    skillBindings: [binding("payments.account.statement", "payments.account.statement")],
    status: "implemented",
    version: "1.0.0",
  },
  {
    description: "Crear una nota interna en una conversacion de Inbox.",
    enabled: true,
    id: "inbox.note.create",
    kind: "command",
    module: "whapp",
    name: "Crear nota interna Inbox",
    requiredPermissions: ["inbox.conversations.reply"],
    skillBindings: [binding("inbox.note.create", "inbox.note.create")],
    status: "implemented",
    version: "1.0.0",
  },
  {
    description: "Vincular una conversacion de Inbox con un cliente existente.",
    enabled: true,
    id: "inbox.customer.link",
    kind: "command",
    module: "whapp",
    name: "Vincular cliente Inbox",
    requiredPermissions: ["inbox.conversations.assign", "crm.customers.view"],
    skillBindings: [binding("inbox.customer.link", "inbox.customer.link")],
    status: "implemented",
    version: "1.0.0",
  },
  {
    description: "Asignar una conversacion de Inbox a un usuario responsable.",
    enabled: true,
    id: "inbox.conversation.assign",
    kind: "command",
    module: "whapp",
    name: "Asignar conversacion Inbox",
    requiredPermissions: ["inbox.conversations.assign"],
    skillBindings: [binding("inbox.conversation.assign", "inbox.conversation.assign")],
    status: "implemented",
    version: "1.0.0",
  },
  {
    description: "Consultar conversaciones de Inbox con SLA vencido o en riesgo.",
    enabled: true,
    id: "inbox.sla.overdue.query",
    kind: "query",
    module: "whapp",
    name: "Consultar SLA vencido Inbox",
    requiredPermissions: ["inbox.conversations.view"],
    skillBindings: [binding("inbox.sla.overdue.query", "inbox.sla.overdue.query")],
    status: "implemented",
    version: "1.0.0",
  },
  {
    description: "Cerrar una conversacion de Inbox con trazabilidad.",
    enabled: true,
    id: "inbox.conversation.close",
    kind: "command",
    module: "whapp",
    name: "Cerrar conversacion Inbox",
    requiredPermissions: ["inbox.conversations.status.change"],
    skillBindings: [binding("inbox.conversation.close", "inbox.conversation.close")],
    status: "implemented",
    version: "1.0.0",
  },
  {
    description: "Validar calidad, estructura y datos de un articulo Autoblog.",
    enabled: true,
    id: "autoblog.article.validate",
    kind: "analysis",
    module: "autoblog",
    name: "Validar articulo Autoblog",
    requiredPermissions: ["autoblog.view"],
    skillBindings: [binding("autoblog.article.validate", "autoblog.article.validate")],
    status: "implemented",
    version: "1.0.0",
  },
  {
    description: "Normalizar salida de IA de Autoblog antes de guardar o publicar.",
    enabled: true,
    id: "autoblog.output.normalize",
    kind: "command",
    module: "autoblog",
    name: "Normalizar salida Autoblog",
    requiredPermissions: ["autoblog.edit"],
    skillBindings: [binding("autoblog.output.normalize", "autoblog.output.normalize")],
    status: "implemented",
    version: "1.0.0",
  },
  {
    description: "Consultar senales operativas y comerciales detectadas por Brain.",
    enabled: true,
    id: "brain.signals.query",
    kind: "analysis",
    module: "brain",
    name: "Consultar senales Brain",
    requiredPermissions: ["brain.insights.view"],
    skillBindings: [binding("brain.signals.query", "brain.signals.query")],
    status: "implemented",
    version: "1.0.0",
  },
  {
    description: "Consultar recomendaciones accionables generadas por Brain.",
    enabled: true,
    id: "brain.recommendations.query",
    kind: "analysis",
    module: "brain",
    name: "Consultar recomendaciones Brain",
    requiredPermissions: ["brain.recommendations.view"],
    skillBindings: [binding("brain.recommendations.query", "brain.recommendations.query")],
    status: "implemented",
    version: "1.0.0",
  },
  {
    description: "Preparar un plan ejecutable compuesto por capabilities autorizadas.",
    enabled: true,
    id: "brain.plan.prepare",
    kind: "draft",
    module: "brain",
    name: "Preparar plan Brain",
    requiredPermissions: ["brain.recommendations.view"],
    skillBindings: [binding("brain.plan.prepare", "brain.plan.prepare")],
    status: "implemented",
    version: "1.0.0",
  },
];

export const initialCapabilities: CapabilityDefinition[] = [
  {
    description: "Buscar clientes o prospectos por nombre, identificacion, correo o telefono.",
    enabled: true,
    id: "crm.customer.search",
    kind: "query",
    module: "crm",
    name: "Buscar cliente",
    requiredPermissions: ["crm.customers.view"],
    skillBindings: [binding("crm.customer.search", "crm.customer.search")],
    status: "implemented",
    version: "1.0.0",
  },
  {
    description: "Crear un cliente o prospecto CRM con validacion de datos minimos.",
    enabled: true,
    id: "crm.customer.create",
    kind: "command",
    module: "crm",
    name: "Crear cliente",
    requiredPermissions: ["crm.customers.create"],
    skillBindings: [binding("crm.customer.create", "crm.customer.create")],
    status: "implemented",
    version: "1.0.0",
  },
  {
    description: "Recomendar el siguiente cliente a atender usando senales comerciales reales.",
    enabled: true,
    id: "crm.customer.next_best",
    kind: "analysis",
    module: "crm",
    name: "Siguiente mejor cliente",
    requiredPermissions: ["crm.customers.view", "sales.orders.view"],
    skillBindings: [
      binding(
        "crm.customer.next_best",
        "crm.customer.next_best.execute.v1",
        "planned",
      ),
    ],
    status: "planned",
    version: "1.0.0",
  },
  {
    description: "Buscar productos o servicios por nombre, codigo o descripcion.",
    enabled: true,
    id: "catalog.product.search",
    kind: "query",
    module: "catalog",
    name: "Buscar producto",
    requiredPermissions: ["catalog.products.view"],
    skillBindings: [binding("catalog.product.search", "catalog.product.search")],
    status: "implemented",
    version: "1.0.0",
  },
  {
    description: "Crear un producto o servicio comercial basico.",
    enabled: true,
    id: "catalog.product.create",
    kind: "command",
    module: "catalog",
    name: "Crear producto",
    requiredPermissions: ["catalog.products.create"],
    skillBindings: [binding("catalog.product.create", "catalog.product.create")],
    status: "implemented",
    version: "1.0.0",
  },
  {
    description: "Consultar existencias por producto o bodega.",
    enabled: true,
    id: "inventory.stock.query",
    kind: "query",
    module: "inventory",
    name: "Consultar stock",
    requiredPermissions: ["inventory.stock.view"],
    skillBindings: [binding("inventory.stock.query", "inventory.stock.query")],
    status: "implemented",
    version: "1.0.0",
  },
  {
    description: "Sugerir reposicion o revision de inventario sin ajustar stock automaticamente.",
    enabled: true,
    id: "inventory.reorder.suggest",
    kind: "draft",
    module: "inventory",
    name: "Sugerir reorden de inventario",
    requiredPermissions: ["inventory.stock.view"],
    skillBindings: [binding("inventory.reorder.suggest", "inventory.reorder.suggest")],
    status: "implemented",
    version: "1.0.0",
  },
  {
    description: "Consultar ventas recientes o por numero, estado o nota.",
    enabled: true,
    id: "sales.summary.query",
    kind: "query",
    module: "sales",
    name: "Buscar ventas",
    requiredPermissions: ["sales.orders.view"],
    skillBindings: [binding("sales.summary.query", "sales.summary.query")],
    status: "implemented",
    version: "1.0.0",
  },
  {
    description: "Crear una cotizacion o proforma validada.",
    enabled: true,
    id: "quotes.draft.create",
    kind: "draft",
    module: "quotes",
    name: "Crear borrador de proforma",
    requiredPermissions: ["quotes.create"],
    skillBindings: [binding("quotes.draft.create", "quotes.draft.create")],
    status: "implemented",
    version: "1.0.0",
  },
  {
    description: "Crear una tarea propia como notificacion operativa.",
    enabled: true,
    id: "agenda.task.create",
    kind: "command",
    module: "agenda",
    name: "Crear tarea",
    requiredPermissions: ["crm.followups.create"],
    skillBindings: [binding("agenda.task.create", "agenda.task.create")],
    status: "implemented",
    version: "1.0.0",
  },
  {
    description: "Consultar cuentas por cobrar vencidas o pendientes.",
    enabled: true,
    id: "payments.overdue.query",
    kind: "query",
    module: "payments",
    name: "Consultar cobros vencidos",
    requiredPermissions: ["payments.accounts.view"],
    skillBindings: [binding("payments.overdue.query", "payments.overdue.query")],
    status: "implemented",
    version: "1.0.0",
  },
  {
    description: "Consultar cuentas por pagar pendientes o vencidas.",
    enabled: true,
    id: "payments.payable.query",
    kind: "query",
    module: "payments",
    name: "Consultar cuentas por pagar",
    requiredPermissions: ["payments.accounts.view"],
    skillBindings: [binding("payments.payable.query", "payments.payable.query")],
    status: "implemented",
    version: "1.0.0",
  },
  {
    description: "Crear una tarea para atender cobros vencidos.",
    enabled: true,
    id: "payments.collection-reminder.create",
    kind: "command",
    module: "payments",
    name: "Crear recordatorio de cobro",
    requiredPermissions: ["payments.accounts.view"],
    skillBindings: [
      binding(
        "payments.collection-reminder.create",
        "payments.collection-reminder.create",
      ),
    ],
    status: "implemented",
    version: "1.0.0",
  },
  {
    description: "Consultar ordenes de compra abiertas o emitidas.",
    enabled: true,
    id: "purchases.order.query",
    kind: "query",
    module: "purchases",
    name: "Consultar ordenes de compra",
    requiredPermissions: ["purchases.orders.view"],
    skillBindings: [binding("purchases.order.query", "purchases.order.query")],
    status: "implemented",
    version: "1.0.0",
  },
  {
    description: "Preparar una sugerencia de compra basada en stock bajo.",
    enabled: true,
    id: "purchases.reorder.suggest",
    kind: "draft",
    module: "purchases",
    name: "Preparar sugerencia de compra",
    requiredPermissions: ["purchases.orders.view", "inventory.stock.view"],
    skillBindings: [binding("purchases.reorder.suggest", "purchases.reorder.suggest")],
    status: "implemented",
    version: "1.0.0",
  },
  {
    description: "Consultar despachos pendientes, en preparacion, listos o en ruta.",
    enabled: true,
    id: "dispatch.pending.query",
    kind: "query",
    module: "dispatch",
    name: "Consultar despachos pendientes",
    requiredPermissions: ["dispatch.orders.view"],
    skillBindings: [binding("dispatch.pending.query", "dispatch.pending.query")],
    status: "implemented",
    version: "1.0.0",
  },
  {
    description: "Preparar un borrador fiscal sin emitir documentos.",
    enabled: true,
    id: "billing.draft.prepare",
    kind: "draft",
    module: "billing",
    name: "Preparar borrador fiscal",
    requiredPermissions: ["billing.invoices.create"],
    skillBindings: [binding("billing.draft.prepare", "billing.draft.prepare")],
    status: "implemented",
    version: "1.0.0",
  },
  {
    description: "Preparar una respuesta para Inbox o Whapp sin enviarla.",
    enabled: true,
    id: "inbox.reply.draft",
    kind: "draft",
    module: "whapp",
    name: "Preparar respuesta Inbox",
    requiredPermissions: ["inbox.conversations.reply"],
    skillBindings: [binding("inbox.reply.draft", "inbox.reply.draft")],
    status: "implemented",
    version: "1.0.0",
  },
  {
    description: "Generar un articulo de Autoblog con IA y guardarlo como borrador.",
    enabled: true,
    id: "autoblog.article.generate",
    kind: "command",
    module: "autoblog",
    name: "Generar articulo Autoblog",
    requiredPermissions: ["autoblog.create"],
    skillBindings: [binding("autoblog.article.generate", "autoblog.article.generate")],
    status: "implemented",
    version: "1.0.0",
  },
  {
    description: "Ejecutar el analisis avanzado de Business Brain.",
    enabled: true,
    id: "brain.analysis.run",
    kind: "command",
    module: "brain",
    name: "Generar analisis Brain",
    requiredPermissions: ["brain.settings.manage"],
    skillBindings: [binding("brain.analysis.run", "brain.analysis.run")],
    status: "implemented",
    version: "1.0.0",
  },
  {
    description: "Buscar informacion autorizada y vigente de marca, FAQ, politicas, documentos y catalogo.",
    enabled: true,
    id: "brain.knowledge.search",
    kind: "query",
    module: "brain",
    name: "Buscar conocimiento Brain",
    requiredPermissions: ["brain.insights.view"],
    skillBindings: [binding("brain.knowledge.search", "brain.knowledge.search")],
    status: "implemented",
    version: "1.0.0",
  },
  {
    description: "Sincronizar contexto, marca y catalogo con la base de conocimiento versionada.",
    enabled: true,
    id: "brain.knowledge.sync",
    kind: "command",
    module: "brain",
    name: "Sincronizar conocimiento Brain",
    requiredPermissions: ["brain.settings.manage"],
    skillBindings: [binding("brain.knowledge.sync", "brain.knowledge.sync")],
    status: "implemented",
    version: "1.0.0",
  },
  {
    description: "Responder preguntas estrategicas leyendo Business Brain.",
    enabled: true,
    id: "brain.question.answer",
    kind: "query",
    module: "brain",
    name: "Responder pregunta Brain",
    requiredPermissions: ["brain.insights.view"],
    skillBindings: [binding("brain.question.answer", "brain.question.answer")],
    status: "implemented",
    version: "1.0.0",
  },
  {
    description: "Indicar donde completar el contexto de negocio.",
    enabled: true,
    id: "brain.context.open",
    kind: "query",
    module: "brain",
    name: "Actualizar contexto Brain",
    requiredPermissions: ["brain.insights.view"],
    skillBindings: [binding("brain.context.open", "brain.context.open")],
    status: "implemented",
    version: "1.0.0",
  },
  ...stage2CapabilityContracts,
  ...plannedAgentCapabilities,
];

const stage2BusinessIntentContracts: BusinessIntentDefinition[] = [
  {
    capabilityId: "crm.customer.update",
    description: "Actualizar informacion de un cliente.",
    enabled: true,
    examples: ["actualiza el telefono de Juan", "cambia el correo del cliente Prueba Brain"],
    id: "crm.customer.update",
    module: "crm",
    requiredSlots: [customerQuerySlot, contentSlot],
  },
  {
    capabilityId: "crm.customer.history",
    description: "Consultar historial de compras, ventas o seguimientos de un cliente.",
    enabled: true,
    examples: ["cuanto me compro Juan", "historial del cliente Prueba Brain"],
    id: "crm.customer.history",
    module: "crm",
    requiredSlots: [customerQuerySlot],
  },
  {
    capabilityId: "crm.followup.query",
    description: "Consultar seguimientos CRM.",
    enabled: true,
    examples: ["seguimientos pendientes", "que clientes tengo que llamar"],
    id: "crm.followup.query",
    module: "crm",
    requiredSlots: [],
  },
  {
    capabilityId: "crm.followup.create",
    description: "Crear seguimiento CRM para un cliente, venta o conversacion.",
    enabled: true,
    examples: ["crea seguimiento para Juan manana", "crear tarea de llamar al cliente"],
    id: "crm.followup.create",
    module: "crm",
    optionalSlots: [
      customerQuerySlot,
      quoteReferenceSlot,
      saleReferenceSlot,
      conversationReferenceSlot,
    ],
    requiredSlots: [taskTitleSlot],
  },
  {
    capabilityId: "catalog.product.update",
    description: "Actualizar informacion de un producto.",
    enabled: true,
    examples: ["actualiza el precio del producto guante", "cambia el codigo del producto lentes"],
    id: "catalog.product.update",
    module: "catalog",
    requiredSlots: [productQuerySlot, contentSlot],
  },
  {
    capabilityId: "catalog.product.validate",
    description: "Validar datos de producto.",
    enabled: true,
    examples: ["valida el producto guante", "revisa si este producto esta listo para vender"],
    id: "catalog.product.validate",
    module: "catalog",
    requiredSlots: [productQuerySlot],
  },
  {
    capabilityId: "catalog.product.stock.initialize",
    description: "Inicializar stock de un producto.",
    enabled: true,
    examples: ["inicializa stock del producto guante en principal con 10"],
    id: "catalog.product.stock.initialize",
    module: "catalog",
    requiredSlots: [productQuerySlot, warehouseSlot, quantitySlot],
  },
  {
    capabilityId: "inventory.stock.adjust",
    description: "Ajustar stock de inventario.",
    enabled: true,
    examples: ["ajusta el stock de guante a 10", "corrige inventario de lentes en principal"],
    id: "inventory.stock.adjust",
    module: "inventory",
    requiredSlots: [productQuerySlot, warehouseSlot, quantitySlot],
  },
  {
    capabilityId: "inventory.stock.transfer",
    description: "Transferir stock entre bodegas.",
    enabled: true,
    examples: ["transfiere 5 guantes de principal a ruta", "mueve stock entre bodegas"],
    id: "inventory.stock.transfer",
    module: "inventory",
    requiredSlots: [
      productQuerySlot,
      quantitySlot,
      originWarehouseSlot,
      destinationWarehouseSlot,
    ],
  },
  {
    capabilityId: "quotes.item.add",
    description: "Agregar item a una cotizacion.",
    enabled: true,
    examples: ["agrega dos guantes a la cotizacion", "incluye lentes en la proforma"],
    id: "quotes.item.add",
    module: "quotes",
    requiredSlots: [quoteReferenceSlot, productQuerySlot, quantitySlot],
  },
  {
    capabilityId: "quotes.total.calculate",
    description: "Calcular total de una cotizacion.",
    enabled: true,
    examples: ["calcula el total de la cotizacion", "cuanto da esta proforma"],
    id: "quotes.total.calculate",
    module: "quotes",
    requiredSlots: [quoteReferenceSlot],
  },
  {
    capabilityId: "quotes.expired.query",
    description: "Consultar cotizaciones vencidas o sin respuesta.",
    enabled: true,
    examples: ["cotizaciones vencidas", "proformas sin respuesta"],
    id: "quotes.expired.query",
    module: "quotes",
    requiredSlots: [],
  },
  {
    capabilityId: "quotes.sale.confirm",
    description: "Confirmar una cotizacion como venta.",
    enabled: true,
    examples: ["confirma esta cotizacion como venta", "pasar proforma a venta"],
    id: "quotes.sale.confirm",
    module: "quotes",
    requiredSlots: [quoteReferenceSlot],
  },
  {
    capabilityId: "sales.order.detail",
    description: "Consultar detalle de venta.",
    enabled: true,
    examples: ["detalle de la venta 25", "abre la venta VEN-2026-000027"],
    id: "sales.order.detail",
    module: "sales",
    requiredSlots: [saleReferenceSlot],
  },
  {
    capabilityId: "sales.receivable.generate",
    description: "Generar cuenta por cobrar desde venta.",
    enabled: true,
    examples: ["genera cuenta por cobrar de esta venta"],
    id: "sales.receivable.generate",
    module: "sales",
    requiredSlots: [saleReferenceSlot],
  },
  {
    capabilityId: "sales.dispatch.prepare",
    description: "Preparar despacho desde venta.",
    enabled: true,
    examples: ["prepara despacho de esta venta", "crear despacho para la venta"],
    id: "sales.dispatch.prepare",
    module: "sales",
    requiredSlots: [saleReferenceSlot],
  },
  {
    capabilityId: "payments.payment.register",
    description: "Registrar cobro o abono.",
    enabled: true,
    examples: ["registra cobro de la factura", "aplica pago del cliente"],
    id: "payments.payment.register",
    module: "payments",
    requiredSlots: [accountReferenceSlot, quantitySlot],
  },
  {
    capabilityId: "payments.account.statement",
    description: "Consultar estado de cuenta.",
    enabled: true,
    examples: ["estado de cuenta de Juan", "cuanto debe el cliente Prueba Brain"],
    id: "payments.account.statement",
    module: "payments",
    requiredSlots: [customerQuerySlot],
  },
  {
    capabilityId: "inbox.note.create",
    description: "Crear nota interna de Inbox.",
    enabled: true,
    examples: ["agrega una nota interna al chat", "deja nota en esta conversacion"],
    id: "inbox.note.create",
    module: "whapp",
    requiredSlots: [conversationReferenceSlot, contentSlot],
  },
  {
    capabilityId: "inbox.customer.link",
    description: "Vincular conversacion con cliente.",
    enabled: true,
    examples: ["vincula este chat con Juan", "asocia la conversacion al cliente"],
    id: "inbox.customer.link",
    module: "whapp",
    requiredSlots: [conversationReferenceSlot, customerQuerySlot],
  },
  {
    capabilityId: "inbox.conversation.assign",
    description: "Asignar conversacion de Inbox.",
    enabled: true,
    examples: ["asigna esta conversacion a Maria", "pasar este chat al vendedor"],
    id: "inbox.conversation.assign",
    module: "whapp",
    requiredSlots: [conversationReferenceSlot, assigneeSlot],
  },
  {
    capabilityId: "inbox.sla.overdue.query",
    description: "Consultar conversaciones con SLA vencido.",
    enabled: true,
    examples: ["conversaciones SLA vencido", "chats atrasados"],
    id: "inbox.sla.overdue.query",
    module: "whapp",
    requiredSlots: [],
  },
  {
    capabilityId: "inbox.conversation.close",
    description: "Cerrar conversacion de Inbox.",
    enabled: true,
    examples: ["cierra esta conversacion", "marca este chat como cerrado"],
    id: "inbox.conversation.close",
    module: "whapp",
    requiredSlots: [conversationReferenceSlot],
  },
  {
    capabilityId: "autoblog.article.validate",
    description: "Validar articulo Autoblog.",
    enabled: true,
    examples: ["valida el blog", "revisa este articulo antes de publicar"],
    id: "autoblog.article.validate",
    module: "autoblog",
    requiredSlots: [contentSlot],
  },
  {
    capabilityId: "autoblog.output.normalize",
    description: "Normalizar salida IA de Autoblog.",
    enabled: true,
    examples: ["normaliza el articulo", "limpia la salida del blog"],
    id: "autoblog.output.normalize",
    module: "autoblog",
    requiredSlots: [contentSlot],
  },
  {
    capabilityId: "brain.signals.query",
    description: "Consultar senales de Brain.",
    enabled: true,
    examples: ["que senales ves", "detecta alertas del negocio"],
    id: "brain.signals.query",
    module: "brain",
    requiredSlots: [],
  },
  {
    capabilityId: "brain.recommendations.query",
    description: "Consultar recomendaciones Brain.",
    enabled: true,
    examples: ["que recomiendas hacer", "dame recomendaciones del negocio"],
    id: "brain.recommendations.query",
    module: "brain",
    requiredSlots: [],
  },
  {
    capabilityId: "brain.plan.prepare",
    description: "Preparar plan ejecutable Brain.",
    enabled: true,
    examples: ["prepara un plan de ventas", "arma un plan para mejorar inventario"],
    id: "brain.plan.prepare",
    module: "brain",
    requiredSlots: [contentSlot],
  },
];

export const initialBusinessIntents: BusinessIntentDefinition[] = [
  {
    capabilityId: "crm.customer.search",
    description: "Buscar un cliente o prospecto.",
    enabled: true,
    examples: ["busca al cliente Juan", "encuentra cliente Prueba Brain"],
    id: "crm.customer.search",
    module: "crm",
    requiredSlots: [querySlot],
  },
  {
    capabilityId: "crm.customer.create",
    description: "Crear un cliente o prospecto.",
    enabled: true,
    examples: ["crea un cliente llamado Juan", "registrar cliente nuevo"],
    id: "crm.customer.create",
    module: "crm",
    requiredSlots: [customerNameSlot],
  },
  {
    capabilityId: "crm.customer.next_best",
    description: "Determinar el siguiente cliente que conviene atender.",
    enabled: true,
    examples: ["que cliente debo atender primero", "cual cliente priorizo hoy"],
    id: "crm.customer.next_best",
    module: "crm",
    requiredSlots: [],
  },
  {
    capabilityId: "catalog.product.search",
    description: "Buscar producto o servicio.",
    enabled: true,
    examples: ["busca el producto lentes", "encontrar servicio instalacion"],
    id: "catalog.product.search",
    module: "catalog",
    requiredSlots: [querySlot],
  },
  {
    capabilityId: "catalog.product.create",
    description: "Crear producto o servicio.",
    enabled: true,
    examples: ["crear producto Cable HDMI precio 5000"],
    id: "catalog.product.create",
    module: "catalog",
    requiredSlots: [productNameSlot],
  },
  {
    capabilityId: "inventory.stock.query",
    description: "Consultar stock o inventario de un producto.",
    enabled: true,
    examples: ["cuanto stock hay de lentes", "inventario del producto cable"],
    id: "inventory.stock.query",
    module: "inventory",
    requiredSlots: [querySlot],
  },
  {
    capabilityId: "inventory.reorder.suggest",
    description: "Sugerir reorden de inventario.",
    enabled: true,
    examples: ["que productos tienen stock bajo", "sugerir reorden"],
    id: "inventory.reorder.suggest",
    module: "inventory",
    requiredSlots: [],
  },
  {
    capabilityId: "sales.summary.query",
    description: "Consultar ventas recientes o por criterio.",
    enabled: true,
    examples: ["muestrame ventas recientes", "consultar ventas"],
    id: "sales.summary.query",
    module: "sales",
    requiredSlots: [],
  },
  {
    capabilityId: "quotes.draft.create",
    description: "Crear borrador de cotizacion.",
    enabled: true,
    examples: ["crear cotizacion", "preparar proforma"],
    id: "quotes.draft.create",
    module: "quotes",
    requiredSlots: [quoteItemsSlot],
  },
  {
    capabilityId: "agenda.task.create",
    description: "Crear tarea o seguimiento.",
    enabled: true,
    examples: ["crear tarea llamar cliente", "agendar seguimiento"],
    id: "agenda.task.create",
    module: "agenda",
    requiredSlots: [taskTitleSlot],
  },
  {
    capabilityId: "payments.overdue.query",
    description: "Consultar cobros vencidos.",
    enabled: true,
    examples: ["cobros vencidos", "cuentas por cobrar pendientes"],
    id: "payments.overdue.query",
    module: "payments",
    requiredSlots: [],
  },
  {
    capabilityId: "payments.payable.query",
    description: "Consultar cuentas por pagar pendientes o vencidas.",
    enabled: true,
    examples: ["cuentas por pagar pendientes", "pagos a proveedores pendientes"],
    id: "payments.payable.query",
    module: "payments",
    requiredSlots: [],
  },
  {
    capabilityId: "payments.collection-reminder.create",
    description: "Crear recordatorio de cobro.",
    enabled: true,
    examples: ["crear recordatorio de cobro", "preparar cobros"],
    id: "payments.collection-reminder.create",
    module: "payments",
    requiredSlots: [],
  },
  {
    capabilityId: "purchases.order.query",
    description: "Consultar ordenes de compra.",
    enabled: true,
    examples: ["ordenes de compra pendientes", "consultar compras"],
    id: "purchases.order.query",
    module: "purchases",
    requiredSlots: [],
  },
  {
    capabilityId: "purchases.reorder.suggest",
    description: "Preparar sugerencia de compra.",
    enabled: true,
    examples: ["que productos debo comprar", "sugerir compra"],
    id: "purchases.reorder.suggest",
    module: "purchases",
    requiredSlots: [],
  },
  {
    capabilityId: "dispatch.pending.query",
    description: "Consultar despachos pendientes.",
    enabled: true,
    examples: ["despachos pendientes", "entregas pendientes"],
    id: "dispatch.pending.query",
    module: "dispatch",
    requiredSlots: [],
  },
  {
    capabilityId: "billing.draft.prepare",
    description: "Preparar borrador fiscal.",
    enabled: true,
    examples: ["preparar factura", "crear borrador fiscal"],
    id: "billing.draft.prepare",
    module: "billing",
    requiredSlots: [],
  },
  {
    capabilityId: "inbox.reply.draft",
    description: "Preparar respuesta para Inbox o WhatsApp.",
    enabled: true,
    examples: ["preparar respuesta whatsapp", "responder inbox"],
    id: "inbox.reply.draft",
    module: "whapp",
    requiredSlots: [conversationReferenceSlot],
  },
  {
    capabilityId: "autoblog.article.generate",
    description: "Generar articulo de Autoblog.",
    enabled: true,
    examples: ["crear blog sobre inventario", "generar articulo"],
    id: "autoblog.article.generate",
    module: "autoblog",
    requiredSlots: [blogTopicSlot],
  },
  {
    capabilityId: "brain.analysis.run",
    description: "Ejecutar analisis Brain.",
    enabled: true,
    examples: ["analiza mi negocio", "ejecuta el brain"],
    id: "brain.analysis.run",
    module: "brain",
    requiredSlots: [],
  },
  {
    capabilityId: "brain.knowledge.search",
    description: "Consultar conocimiento verificado del negocio.",
    enabled: true,
    examples: ["que dice nuestra politica de devoluciones", "cual es el horario", "que ofrecemos"],
    id: "brain.knowledge.search",
    module: "brain",
    requiredSlots: [querySlot],
  },
  {
    capabilityId: "brain.knowledge.sync",
    description: "Actualizar la base de conocimiento de Brain.",
    enabled: true,
    examples: ["sincroniza lo que sabes de mi empresa", "actualiza marca y catalogo en brain"],
    id: "brain.knowledge.sync",
    module: "brain",
    requiredSlots: [],
  },
  {
    capabilityId: "brain.question.answer",
    description: "Responder pregunta estrategica general.",
    enabled: true,
    examples: ["como va mi negocio", "que esta pasando esta semana"],
    id: "brain.question.answer",
    module: "brain",
    requiredSlots: [],
  },
  {
    capabilityId: "brain.context.open",
    description: "Abrir contexto de negocio.",
    enabled: true,
    examples: ["actualizar contexto", "completar contexto del negocio"],
    id: "brain.context.open",
    module: "brain",
    requiredSlots: [],
  },
  ...stage2BusinessIntentContracts,
];
