import type {
  BrainAgentDefinition,
  BrainAutomationJobDefinition,
  BrainTaskSuccessMetricDefinition,
  BrainWorkflowDefinition,
} from "@/modules/brain/runtime/contracts";
import { agentCapabilityExpansionIds } from "@/modules/brain/runtime/agent-capability-expansion";

type BrainAgentCatalogSeed = Omit<
  BrainAgentDefinition,
  "budget" | "instructions" | "limits" | "successCriteria"
>;

const agentDefaults = (agent: BrainAgentCatalogSeed): BrainAgentDefinition => ({
  ...agent,
  budget: {
    maxCostUsd: 1,
    maxDurationSeconds: 300,
    maxTokens: 12_000,
  },
  instructions: [
    agent.description,
    "Consulta datos mediante Skills autorizadas y nunca accedas directamente a la base.",
    "Entrega evidencia, riesgos, pendientes y un resultado verificable al Supervisor.",
  ],
  limits: {
    maxConcurrentTasks: 3,
    maxDelegationDepth: 1,
  },
  successCriteria: [
    "El resultado responde al objetivo asignado.",
    "Toda cifra o entidad proviene de una Skill autorizada.",
    "No quedan acciones sensibles ejecutadas sin aprobación.",
  ],
});

export const initialBrainAgents: BrainAgentDefinition[] = ([
  {
    capabilityIds: [
      "crm.customer.search",
      "crm.customer.create",
      "crm.customer.history",
      "quotes.draft.create",
      "quotes.item.add",
      "quotes.sale.confirm",
      "sales.summary.query",
      "sales.order.detail",
      ...agentCapabilityExpansionIds.ventas,
    ],
    description: "Gestiona oportunidades, clientes, cotizaciones y ventas.",
    id: "ventas",
    module: "sales",
    name: "Agente de Ventas",
    requiredPermissions: ["crm.customers.view", "quotes.view", "sales.orders.view"],
    version: "1.0.0",
  },
  {
    capabilityIds: [
      "payments.overdue.query",
      "payments.payable.query",
      "payments.account.statement",
      "payments.payment.register",
      "sales.receivable.generate",
      ...agentCapabilityExpansionIds.finanzas,
    ],
    description: "Supervisa cobros, pagos, cuentas vencidas y cartera.",
    id: "finanzas",
    module: "payments",
    name: "Agente de Finanzas",
    requiredPermissions: ["payments.accounts.view"],
    version: "1.0.0",
  },
  {
    capabilityIds: [
      "inventory.stock.query",
      "inventory.reorder.suggest",
      "inventory.stock.adjust",
      "inventory.stock.transfer",
      "catalog.product.search",
      "catalog.product.validate",
      ...agentCapabilityExpansionIds.inventario,
    ],
    description: "Cuida stock, quiebres, bodegas y movimientos de inventario.",
    id: "inventario",
    module: "inventory",
    name: "Agente de Inventario",
    requiredPermissions: ["inventory.stock.view"],
    version: "1.0.0",
  },
  {
    capabilityIds: [
      "dispatch.pending.query",
      "sales.dispatch.prepare",
      "sales.order.detail",
      ...agentCapabilityExpansionIds.logistica,
    ],
    description: "Coordina despachos, entregas pendientes y preparacion logistica.",
    id: "logistica",
    module: "dispatch",
    name: "Agente de Logistica",
    requiredPermissions: ["dispatch.orders.view"],
    version: "1.0.0",
  },
  {
    capabilityIds: [
      "purchases.order.query",
      "inventory.reorder.suggest",
      "catalog.product.search",
      ...agentCapabilityExpansionIds.compras,
    ],
    description: "Apoya compras pendientes, reposicion y revision de proveedores.",
    id: "compras",
    module: "purchases",
    name: "Agente de Compras",
    requiredPermissions: ["purchases.orders.view"],
    version: "1.0.0",
  },
  {
    capabilityIds: [
      "inbox.reply.draft",
      "inbox.note.create",
      "inbox.customer.link",
      "inbox.conversation.assign",
      "inbox.conversation.close",
      ...agentCapabilityExpansionIds.soporte,
    ],
    description: "Atiende Inbox y WhatsApp con borradores y acciones controladas.",
    id: "soporte",
    module: "whapp",
    name: "Agente de Soporte",
    requiredPermissions: ["inbox.conversations.view", "inbox.conversations.reply"],
    version: "1.0.0",
  },
  {
    capabilityIds: [
      "autoblog.article.generate",
      "autoblog.article.validate",
      "autoblog.output.normalize",
      ...agentCapabilityExpansionIds.contenido,
    ],
    description: "Produce y valida contenido operativo y comercial.",
    id: "contenido",
    module: "autoblog",
    name: "Agente de Contenido",
    requiredPermissions: ["autoblog.view"],
    version: "1.0.0",
  },
  {
    capabilityIds: [
      "autoblog.article.generate",
      "autoblog.article.validate",
      "autoblog.output.normalize",
      "brain.recommendations.query",
      ...agentCapabilityExpansionIds.marketing,
    ],
    description:
      "Responsable de Autoblog, campanas, articulos, SEO, reutilizacion de contenido y oportunidades de comunicacion.",
    id: "marketing",
    module: "autoblog",
    name: "Agente de Marketing",
    requiredPermissions: ["autoblog.view", "brain.insights.view"],
    version: "1.0.0",
  },
  {
    capabilityIds: [
      "brain.analysis.run",
      "brain.signals.query",
      "brain.recommendations.query",
      "brain.question.answer",
      "brain.knowledge.search",
      "brain.plan.prepare",
      ...agentCapabilityExpansionIds.operaciones,
    ],
    description: "Orquesta senales, prioridades, planes y coordinacion general.",
    id: "operaciones",
    module: "brain",
    name: "Agente de Operaciones",
    requiredPermissions: ["brain.insights.view"],
    version: "1.0.0",
  },
  {
    capabilityIds: [
      "brain.question.answer",
      "brain.knowledge.search",
      "brain.knowledge.sync",
      "brain.recommendations.query",
      ...agentCapabilityExpansionIds.rrhh,
    ],
    description: "Monitorea equipo, estados laborales y necesidades de RRHH.",
    id: "rrhh",
    module: "hr",
    name: "Agente de RRHH",
    requiredPermissions: ["hr.timesheets.view"],
    version: "1.0.0",
  },
] satisfies BrainAgentCatalogSeed[]).map(agentDefaults);

export const initialBrainWorkflows: BrainWorkflowDefinition[] = [
  {
    agentIds: ["ventas", "finanzas", "logistica"],
    description:
      "Convierte una intencion comercial en cotizacion, venta, cuenta por cobrar, despacho y seguimiento.",
    id: "commercial.quote_to_dispatch",
    maxConcurrency: 2,
    name: "Cotizacion a despacho",
    successMetricId: "workflow.commercial.quote_to_dispatch.completed",
    version: "1.0.0",
    steps: [
      {
        capabilityId: "quotes.draft.create",
        id: "create_quote",
        name: "Crear cotizacion",
        required: true,
        requiresApproval: false,
        status: "ready",
      },
      {
        capabilityId: "quotes.sale.confirm",
        dependsOn: ["create_quote"],
        id: "confirm_sale",
        name: "Confirmar venta",
        required: true,
        requiresApproval: true,
        status: "approval_required",
      },
      {
        capabilityId: "sales.receivable.generate",
        dependsOn: ["confirm_sale"],
        id: "generate_receivable",
        name: "Generar CxC",
        required: true,
        requiresApproval: true,
        status: "approval_required",
      },
      {
        capabilityId: "sales.dispatch.prepare",
        dependsOn: ["confirm_sale"],
        id: "prepare_dispatch",
        name: "Preparar despacho",
        required: true,
        requiresApproval: true,
        status: "approval_required",
      },
      {
        capabilityId: "crm.followup.create",
        dependsOn: ["confirm_sale"],
        id: "create_followup",
        name: "Crear seguimiento",
        required: true,
        requiresApproval: false,
        status: "planned",
      },
    ],
  },
  {
    agentIds: ["ventas", "finanzas"],
    description: "Confirma una cotizacion aprobada como venta y deja cartera lista.",
    id: "commercial.sale_confirmation",
    maxConcurrency: 2,
    name: "Confirmacion comercial",
    successMetricId: "workflow.commercial.sale_confirmation.completed",
    version: "1.0.0",
    steps: [
      {
        capabilityId: "quotes.sale.confirm",
        id: "confirm_sale",
        name: "Confirmar venta",
        required: true,
        requiresApproval: true,
        status: "approval_required",
      },
      {
        capabilityId: "sales.receivable.generate",
        dependsOn: ["confirm_sale"],
        id: "generate_receivable",
        name: "Generar CxC",
        required: true,
        requiresApproval: true,
        status: "approval_required",
      },
    ],
  },
  {
    agentIds: ["ventas", "soporte"],
    description: "Crea seguimiento posterior a venta o conversacion de cliente.",
    id: "crm.followup_after_sale",
    maxConcurrency: 1,
    name: "Seguimiento posterior",
    successMetricId: "workflow.crm.followup_after_sale.completed",
    version: "1.0.0",
    steps: [
      {
        capabilityId: "crm.followup.create",
        id: "create_followup",
        name: "Crear seguimiento",
        required: true,
        requiresApproval: false,
        status: "planned",
      },
    ],
  },
];

export const initialBrainAutomationJobs: BrainAutomationJobDefinition[] = [
  {
    capabilityId: "payments.overdue.query",
    description: "Detecta cobros vencidos y prepara acciones sugeridas.",
    id: "collections.overdue.scan",
    module: "payments",
    name: "Cobros vencidos",
    schedule: "daily",
    version: "1.0.0",
  },
  {
    capabilityId: "inventory.reorder.suggest",
    description: "Detecta productos con stock bajo y sugiere reposicion.",
    id: "inventory.low_stock.scan",
    module: "inventory",
    name: "Stock bajo",
    schedule: "daily",
    version: "1.0.0",
  },
  {
    capabilityId: "quotes.expired.query",
    description: "Detecta cotizaciones vencidas o sin respuesta para seguimiento.",
    id: "quotes.expired.scan",
    module: "quotes",
    name: "Cotizaciones vencidas",
    schedule: "daily",
    version: "1.0.0",
  },
  {
    capabilityId: "inbox.sla.overdue.query",
    description: "Detecta conversaciones con SLA vencido para priorizacion.",
    id: "conversations.sla.overdue.scan",
    module: "whapp",
    name: "Conversaciones SLA vencido",
    schedule: "hourly",
    version: "1.0.0",
  },
];

export const initialBrainTaskSuccessMetrics: BrainTaskSuccessMetricDefinition[] = [
  {
    description: "Workflow comercial completado de cotizacion a despacho.",
    id: "workflow.commercial.quote_to_dispatch.completed",
    measures: "task_completed",
    name: "Cotizacion a despacho completada",
    workflowId: "commercial.quote_to_dispatch",
  },
  {
    description: "Confirmacion de venta y cuenta por cobrar completadas.",
    id: "workflow.commercial.sale_confirmation.completed",
    measures: "task_completed",
    name: "Confirmacion comercial completada",
    workflowId: "commercial.sale_confirmation",
  },
  {
    description: "Seguimiento posterior creado para el cliente.",
    id: "workflow.crm.followup_after_sale.completed",
    measures: "task_completed",
    name: "Seguimiento creado",
    workflowId: "crm.followup_after_sale",
  },
];
