export type BusinessContext = {
  aiInstructions: string | null;
  brandPersonality: string | null;
  businessHours: string | null;
  businessSummary: string | null;
  competitors: string | null;
  coreValues: string | null;
  createdAt: string;
  createdBy: string | null;
  customerPainPoints: string | null;
  customerServiceRules: string | null;
  differentiators: string | null;
  forbiddenTopics: string | null;
  geographicScope: string | null;
  id: string;
  keywords: string | null;
  mainOffers: string | null;
  mission: string | null;
  notes: string | null;
  operationalRules: string | null;
  preferredCta: string | null;
  pricingNotes: string | null;
  productsServices: string | null;
  requiredDisclaimers: string | null;
  salesRules: string | null;
  serviceAreas: string | null;
  serviceProcess: string | null;
  targetAudience: string | null;
  toneOfVoice: string | null;
  updatedAt: string;
  updatedBy: string | null;
  vision: string | null;
};
