import type { CSSProperties, ReactNode } from "react";

import type { QuoteDocumentCompany, QuoteDocumentSettings } from "@/modules/quotes/quote-document-style";

export type QuoteDocumentLine = { cantidad: number; descripcion: string; impuestoMonto: number; precioUnitario: number; productoCodigo?: string | null; productoNombre?: string | null; total: number };
export type QuoteDocumentData = { clienteNombre: string | null; condiciones?: string | null; creadoPorNombre: string | null; descuentoTotal: number; estado: string; fechaEmision: string | null; fechaVencimiento: string | null; impuestoTotal: number; moneda: string; notas?: string | null; numero: string; subtotal: number; total: number };

type QuoteDocumentLayoutProps = { company: QuoteDocumentCompany; compact?: boolean; data: QuoteDocumentData; items: QuoteDocumentLine[]; settings: QuoteDocumentSettings };

function formatMoney(value: number, currency: string) { return new Intl.NumberFormat("es-CR", { currency, style: "currency" }).format(value); }
function formatDate(value: string | null) { if (!value || value === "draft") return "Pendiente"; return new Intl.DateTimeFormat("es-CR", { dateStyle: "medium" }).format(new Date(`${value}T00:00:00`)); }

function Logo({ company, settings, inverse = false }: Pick<QuoteDocumentLayoutProps, "company" | "settings"> & { inverse?: boolean }) {
  const companyName = company.tradeName || company.name;
  if (settings.logoDataUrl) return <img alt={companyName} className="max-h-14 max-w-36 object-contain object-left" src={settings.logoDataUrl} />; // eslint-disable-line @next/next/no-img-element
  return <span className={`inline-flex size-12 items-center justify-center rounded-xl text-lg font-black ${inverse ? "bg-white text-slate-900" : "text-white"}`} style={inverse ? undefined : { backgroundColor: settings.accentColor }}>{companyName.slice(0, 1).toUpperCase()}</span>;
}

function CompanyDetails({ company, inverse = false }: { company: QuoteDocumentCompany; inverse?: boolean }) {
  const companyName = company.tradeName || company.name;
  return <div className="min-w-0"><p className="text-lg font-black tracking-tight">{companyName}</p>{company.name !== companyName ? <p className={`text-xs ${inverse ? "text-white/75" : "text-slate-500"}`}>{company.name}</p> : null}<p className={`mt-1 text-[11px] leading-4 ${inverse ? "text-white/75" : "text-slate-500"}`}>{[company.identification ? `Cédula ${company.identification}` : null, company.phone, company.email].filter(Boolean).join(" · ")}</p></div>;
}

function Metadata({ data, className = "" }: { data: QuoteDocumentData; className?: string }) {
  return <div className={`grid grid-cols-2 gap-x-5 gap-y-2 text-xs ${className}`}><div><p className="uppercase tracking-[0.12em] opacity-60">Fecha</p><p className="mt-0.5 font-semibold">{formatDate(data.fechaEmision)}</p></div><div><p className="uppercase tracking-[0.12em] opacity-60">Vigencia</p><p className="mt-0.5 font-semibold">{formatDate(data.fechaVencimiento)}</p></div><div><p className="uppercase tracking-[0.12em] opacity-60">Moneda</p><p className="mt-0.5 font-semibold">{data.moneda}</p></div><div><p className="uppercase tracking-[0.12em] opacity-60">Preparó</p><p className="mt-0.5 truncate font-semibold">{data.creadoPorNombre || "Equipo comercial"}</p></div></div>;
}

function Recipient({ data, className = "" }: { data: QuoteDocumentData; className?: string }) { return <section className={className}><p className="text-[10px] font-bold uppercase tracking-[0.18em] text-slate-500">Propuesta para</p><p className="mt-1 text-base font-bold text-slate-950">{data.clienteNombre || "Cliente por definir"}</p><p className="mt-1 text-xs text-slate-500">{data.estado === "borrador" ? "Documento en preparación" : `Estado: ${data.estado}`}</p></section>; }

function ItemsTable({ data, items, variant = "standard" }: Pick<QuoteDocumentLayoutProps, "data" | "items"> & { variant?: "standard" | "dark" | "line" }) {
  const head = variant === "dark" ? "bg-slate-900 text-white" : variant === "line" ? "border-y-2 border-slate-950 text-slate-900" : "bg-slate-100 text-slate-600";
  return <div className="overflow-hidden"><table className="w-full border-collapse text-left text-xs"><thead><tr className={`${head} text-[10px] font-bold uppercase tracking-[0.1em]`}><th className="px-3 py-2.5">Descripción</th><th className="px-2 py-2.5 text-right">Cant.</th><th className="px-2 py-2.5 text-right">Precio</th><th className="px-3 py-2.5 text-right">Importe</th></tr></thead><tbody>{items.length ? items.map((item, index) => <tr className="border-b border-slate-200" key={`${item.descripcion}-${index}`}><td className="px-3 py-3"><p className="font-semibold text-slate-900">{item.descripcion}</p>{item.productoNombre ? <p className="mt-0.5 text-[10px] text-slate-500">{item.productoCodigo ? `${item.productoCodigo} · ` : ""}{item.productoNombre}</p> : null}</td><td className="px-2 py-3 text-right text-slate-600">{item.cantidad}</td><td className="px-2 py-3 text-right text-slate-600">{formatMoney(item.precioUnitario, data.moneda)}</td><td className="px-3 py-3 text-right font-bold text-slate-900">{formatMoney(item.total, data.moneda)}</td></tr>) : <tr><td className="px-3 py-12 text-center text-slate-400" colSpan={4}>Agrega productos o servicios para ver el detalle.</td></tr>}</tbody></table></div>;
}

function Totals({ data, settings, boxed = false }: Pick<QuoteDocumentLayoutProps, "data" | "settings"> & { boxed?: boolean }) { return <section className={`ml-auto w-full max-w-[230px] space-y-1.5 text-xs ${boxed ? "rounded-xl p-4" : "pt-2"}`} style={boxed ? { backgroundColor: `${settings.accentColor}12` } : undefined}><div className="flex justify-between gap-5"><span className="text-slate-500">Subtotal</span><span>{formatMoney(data.subtotal, data.moneda)}</span></div><div className="flex justify-between gap-5"><span className="text-slate-500">Descuento</span><span>{formatMoney(data.descuentoTotal, data.moneda)}</span></div><div className="flex justify-between gap-5"><span className="text-slate-500">Impuestos</span><span>{formatMoney(data.impuestoTotal, data.moneda)}</span></div><div className="mt-3 flex justify-between gap-5 border-t-2 pt-3 text-base font-black" style={{ borderColor: settings.accentColor }}><span>Total</span><span style={{ color: settings.accentColor }}>{formatMoney(data.total, data.moneda)}</span></div></section>; }

function Notes({ data }: Pick<QuoteDocumentLayoutProps, "data" | "settings">) { const content = data.condiciones || data.notas; if (!content) return null; return <section className="mt-7 grid gap-5 border-t pt-5 text-xs md:grid-cols-2"><div><p className="font-bold uppercase tracking-[0.14em] text-slate-500">Condiciones</p><p className="mt-2 whitespace-pre-wrap leading-5 text-slate-600">{data.condiciones || "Según lo conversado con el cliente."}</p></div>{data.notas ? <div><p className="font-bold uppercase tracking-[0.14em] text-slate-500">Notas</p><p className="mt-2 whitespace-pre-wrap leading-5 text-slate-600">{data.notas}</p></div> : null}</section>; }

function Executive({ company, data, items, settings }: QuoteDocumentLayoutProps) { return <><header className="grid gap-5 border-b-4 pb-5 md:grid-cols-[1fr_190px]" style={{ borderColor: settings.accentColor }}><div className="flex items-start gap-3"><Logo company={company} settings={settings} /><CompanyDetails company={company} /></div><div className="border-l pl-4 text-right"><p className="text-[11px] font-bold uppercase tracking-[0.2em] text-slate-500">{settings.documentLabel}</p><p className="mt-1 text-3xl font-black" style={{ color: settings.accentColor }}>{data.numero}</p><p className="mt-1 text-xs text-slate-500">Propuesta comercial</p></div></header><div className="mt-5 grid gap-5 md:grid-cols-[1fr_1.15fr]"><Recipient data={data} className="rounded-xl bg-slate-50 p-4" /><Metadata data={data} className="rounded-xl border p-4" /></div><div className="mt-6"><ItemsTable data={data} items={items} /></div><Totals data={data} settings={settings} boxed /><Notes data={data} settings={settings} /></>; }
function Bold({ company, data, items, settings }: QuoteDocumentLayoutProps) { return <><header className="rounded-2xl p-6 text-white" style={{ backgroundColor: settings.accentColor }}><div className="flex flex-wrap justify-between gap-6"><div className="flex items-start gap-3"><Logo company={company} settings={settings} inverse /><CompanyDetails company={company} inverse /></div><div className="text-right"><p className="text-xs font-bold uppercase tracking-[0.2em] text-white/75">{settings.documentLabel}</p><p className="mt-1 text-4xl font-black">{data.numero}</p></div></div><div className="mt-7 border-t border-white/30 pt-4"><Metadata data={data} className="text-white" /></div></header><div className="mt-6 grid gap-6 md:grid-cols-[1fr_210px]"><div><Recipient data={data} className="border-l-4 pl-4" /><div className="mt-6"><ItemsTable data={data} items={items} variant="dark" /></div></div><div className="flex flex-col justify-end"><p className="text-xs leading-5 text-slate-500">Esta propuesta está preparada especialmente para tu cliente.</p><div className="mt-6 rounded-2xl p-5 text-white" style={{ backgroundColor: settings.accentColor }}><p className="text-[10px] font-bold uppercase tracking-[0.18em] text-white/70">Total propuesto</p><p className="mt-2 text-2xl font-black">{formatMoney(data.total, data.moneda)}</p></div></div></div><Totals data={data} settings={settings} /><Notes data={data} settings={settings} /></>; }
function Minimal({ company, data, items, settings }: QuoteDocumentLayoutProps) { return <><header className="flex flex-wrap items-end justify-between gap-6 border-b pb-6"><div className="flex items-center gap-3"><Logo company={company} settings={settings} /><CompanyDetails company={company} /></div><div className="text-right"><p className="text-4xl font-light tracking-tight text-slate-950">{settings.documentLabel}</p><p className="mt-1 text-xs tracking-[0.18em] text-slate-500">N.º {data.numero}</p></div></header><div className="mt-10 grid gap-6 md:grid-cols-[1fr_1.25fr]"><Recipient data={data} /><Metadata data={data} /></div><div className="mt-10"><ItemsTable data={data} items={items} variant="line" /></div><div className="mt-8 border-t pt-4"><Totals data={data} settings={settings} /></div><Notes data={data} settings={settings} /></>; }
function Editorial({ company, data, items, settings }: QuoteDocumentLayoutProps) { return <div className="grid gap-6 md:grid-cols-[150px_1fr]"><aside className="flex flex-col justify-between rounded-2xl p-5 text-white" style={{ backgroundColor: settings.accentColor }}><div><Logo company={company} settings={settings} inverse /><div className="mt-5"><CompanyDetails company={company} inverse /></div></div><div className="mt-10"><p className="text-[10px] font-bold uppercase tracking-[0.18em] text-white/70">{settings.documentLabel}</p><p className="mt-2 break-all text-3xl font-black leading-none">{data.numero}</p></div></aside><div><header className="border-b-8 pb-5" style={{ borderColor: settings.accentColor }}><p className="text-[11px] font-bold uppercase tracking-[0.18em] text-slate-500">Propuesta comercial</p><h1 className="mt-2 text-3xl font-black tracking-tight text-slate-950">Una propuesta hecha para avanzar.</h1></header><div className="mt-5 grid gap-5 md:grid-cols-2"><Recipient data={data} /><Metadata data={data} /></div><div className="mt-7"><ItemsTable data={data} items={items} /></div><Totals data={data} settings={settings} boxed /><Notes data={data} settings={settings} /></div></div>; }
function Classic({ company, data, items, settings }: QuoteDocumentLayoutProps) { return <div className="border-2 p-2" style={{ borderColor: settings.accentColor }}><div className="border p-6" style={{ borderColor: settings.accentColor }}><header className="flex flex-wrap justify-between gap-5 border-b-4 pb-5" style={{ borderColor: settings.accentColor }}><div className="flex gap-3"><Logo company={company} settings={settings} /><CompanyDetails company={company} /></div><div className="text-right"><p className="font-serif text-2xl font-bold uppercase tracking-[0.12em]">{settings.documentLabel}</p><p className="mt-1 text-xl font-bold" style={{ color: settings.accentColor }}>N.º {data.numero}</p></div></header><div className="mt-5 grid gap-5 border-b pb-5 md:grid-cols-2"><Recipient data={data} /><Metadata data={data} /></div><div className="mt-6"><ItemsTable data={data} items={items} /></div><Totals data={data} settings={settings} /><Notes data={data} settings={settings} /></div></div>; }

export function QuoteDocumentLayout({ company, compact = false, data, items, settings }: QuoteDocumentLayoutProps) {
  const body: Record<QuoteDocumentSettings["templateCode"], ReactNode> = { bold: <Bold company={company} data={data} items={items} settings={settings} />, classic: <Classic company={company} data={data} items={items} settings={settings} />, editorial: <Editorial company={company} data={data} items={items} settings={settings} />, executive: <Executive company={company} data={data} items={items} settings={settings} />, minimal: <Minimal company={company} data={data} items={items} settings={settings} /> };
  const accentStyle = { "--quote-accent": settings.accentColor } as CSSProperties;
  return <article className={`quote-print-document mx-auto w-full bg-white text-slate-950 ${compact ? "min-h-full p-4" : "min-h-[273mm] max-w-[186mm] p-7 print:min-h-0 print:max-w-none print:p-0"}`} style={accentStyle}>{body[settings.templateCode]}<footer className="mt-9 border-t pt-4 text-center text-[11px] text-slate-500">{settings.footerText || "Gracias por considerar nuestra propuesta."}</footer></article>;
}
